name: chatapp
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  emoji_picker_flutter: ^1.6.1 # ✅ Null-safe replacement for `emoji_picker`
  shared_preferences: ^2.2.2
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.9.0
  video_player: ^2.7.2
  socket_io_client: ^2.0.3+1 # ✅ Null-safe version
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-SemiBold.ttf
        - asset: fonts/OpenSans-Italic.ttf
          style: italic
